### ISSUE TITLE
Plot blocks in verde.BlockReduce

### ISSUE THREAD

**Issue by MGomezN** [fatiando/transform2020#4]
[verde.BlockReduce](https://www.fatiando.org/verde/latest/api/generated/verde.BlockReduce.html#verde.BlockReduce) divide the data region into blocks. I want to visualize the blocks at the same time as my data. Is there a simple way to do this?
Thanks

**Comment by santisoler** [comment]
Hi @MGomezN! Good question. 

Sadly there isn't a quick and easy method to get the blocks out of [`verde.BlockReduce`](https://www.fatiando.org/verde/latest/api/generated/verde.BlockReduce.html#verde.BlockReduce) since (1) the blocks are defined when calling the `filter()` and for each particular dataset, and (2) the blocks aren't actually defined, we use a k-d tree to divide the data points instead (Computerphile has a nice video to know more about k-d trees:  https://www.youtube.com/watch?v=BK5x7IUTIyU)

But, we can define *another* `verde.BlockReduce` instance with the same arguments, but with `center_coordiantes=True`.
Then, the output of the `filter()` method contains the coordinates of the center of each block. We can use them to plot the blocks:

```python
import pyproj
import numpy as np
import pandas as pd
import verde as vd
import ensaio
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle


# Downlad sample data
fname = ensaio.fetch_southern_africa_gravity(version=1)
data = pd.read_csv(fname)
data


# Project the data
projection = pyproj.Proj(proj="merc", lat_ts=data.latitude.mean())
easting, northing = projection(data.longitude.values, data.latitude.values)

data = data.assign(easting=easting, northing=northing)
data


# Define a BlockReduce instance, specify center_coordinates=True
spacing = 300e3
reducer = vd.BlockReduce(np.median, spacing=spacing, center_coordinates=True)


# Filter the data and get the coordinates of the center of the blocks
blocks, _ = reducer.filter((data.easting, data.northing), data.gravity_mgal)


# Get the actual spacing of the blocks
easting, northing = np.unique(blocks[0]), np.unique(blocks[1])
d_easting, d_northing = easting[1] - easting[0], northing[1] - northing[0]

print(d_easting, d_northing)


# Plot the data points along with the blocks
plt.scatter(data.easting, data.northing, marker=".")

for easting, northing in zip(blocks[0], blocks[1]):
    rectangle = Rectangle(
        (easting - d_easting / 2, northing - d_northing / 2),
        width=d_easting,
        height=d_northing,
        linewidth=2,
        color="purple",
        fill=False,
    )
    plt.gca().add_patch(rectangle)


plt.gca().set_aspect("equal")
plt.show()
```
![blocks](https://user-images.githubusercontent.com/11541317/168698174-a113540e-3304-4d52-9b20-39ea3bfc895a.png)


Hope it's useful!

**Comment by MGomezN** [comment]
Yes, it was! I took your suggestion and adapted it to my data :)
Thank you for your time
